name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create release with assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref }}
          files: |
            ./build/reliure-linux
            ./build/reliure-macos
            ./build/reliure-win.exe
