name: Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - run: |
          PANDOC_URL=$(curl https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r ".assets[] | select(.name | test(\"amd64.deb$\")) | .browser_download_url")
          curl --silent --show-error --location --fail --retry 4 --retry-delay 5 --output pandoc.deb $PANDOC_URL
          sudo dpkg -i pandoc.deb
          rm pandoc.deb
      - run: pnpm install
      - run: pnpm test
